# Generated by Django 6.0.1 on 2026-02-24 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, help_text='Weight in kg', max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, help_text='Height in cm', max_digits=5)),
                ('systolic_bp', models.IntegerField(help_text='Systolic Blood Pressure (mmHg)')),
                ('diastolic_bp', models.IntegerField(help_text='Diastolic Blood Pressure (mmHg)')),
                ('temperature', models.DecimalField(decimal_places=1, help_text='Temperature in °C', max_digits=4)),
                ('vision', models.CharField(blank=True, help_text='Vision test result (e.g., 20/20)', max_length=50, null=True)),
                ('urine_test', models.CharField(choices=[('normal', 'Normal'), ('abnormal', 'Abnormal'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('school_year', models.CharField(help_text='e.g., 2024-2025', max_length=9)),
                ('checkup_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='students.student')),
            ],
            options={
                'verbose_name': 'Health Record',
                'verbose_name_plural': 'Health Records',
                'ordering': ['-checkup_date'],
            },
        ),
    ]
