# Generated by Django 6.0.1 on 2026-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthrecord',
            name='school_year',
            field=models.CharField(blank=True, help_text='e.g., 2024-2025', max_length=9, null=True),
        ),
    ]
