# Generated by Django 6.0.1 on 2026-02-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_id', models.IntegerField(unique=True, verbose_name='Student ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_initial', models.CharField(blank=True, max_length=5, null=True)),
                ('last_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('address', models.TextField(verbose_name='Home Address')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('department', models.CharField(choices=[('BSIT', 'Bachelor of Science in Information Technology'), ('BSED', 'Bachelor of Secondary Education'), ('BEED', 'Bachelor of Elementary Education'), ('BSHM', 'Bachelor of Science in Hospitality Management'), ('BPEd', 'Bachelor of Physical Education'), ('BSEntrep', 'Bachelor of Science in Entrepreneurship')], default='BSIT', max_length=10)),
                ('year_level', models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year')], default='1', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
